### ISSUE TITLE
Bold doesn't work in PDF

### ISSUE THREAD

**Issue by lorensr** [GraphQLGuide/book#20]
`**two asterisks**` results in text of normal weight.

**Comment by yashaka** [comment]
Try to update [Calibre](https://calibre-ebook.com/download) to the latest version... I had same issue for my gitbook, updating to the version 3.42 fixed it.

**Comment by lorensr** [comment]
Thanks! I was on 3.10, and updating to 3.42 fixed bold in `.mobi`. Bold in `.pdf` remains broken.

**Comment by lorensr** [comment]
Now working
