### ISSUE TITLE
Where are the other formats?

### ISSUE THREAD

**Issue by BigBadaboom** [GraphQLGuide/book#35]
On the store page, it says that the book is available "in HTML, PDF, ePub, and Kindle formats".  After purchasing, (Basic)  I received a link to the HTML version, but I can't find any links to the other versions anywhere. 

There seems to be no download information in the book, the store site, the Github site, the purchase receipt, or my `graphql.guide/me/` page.

Am I simply dense, and missing something obvious?

Regards

**Comment by lorensr** [comment]
You should receive an email to the email address on your GitHub account. I just resent yours, and I'll also add links to the `/me` page ☺️

**Comment by BigBadaboom** [comment]
Thanks for the reply.

I'm not sure where they have gone then.  I have not received those emails.  The only one I have received is the puchase receipt.  I have also checked that they are not in my Gmail spam folder.

**Comment by lorensr** [comment]
Sorry for the trouble! You should now see them at https://graphql.guide/me/ after logging in:

![image](https://user-images.githubusercontent.com/251288/114790808-61960480-9d53-11eb-8e5f-559f258fcedb.png)

**Comment by BigBadaboom** [comment]
Thanks very much for you help.
